research_task:
  description: >
    Analyze the job posting URL provided ({job_posting_url}) 
    to extract key skills, experiences, and qualifications 
    required. Use the tools to gather content and identify 
    and categorize the requirements.
  expected_output: >
    A structured list of job requirements, including necessary 
    skills, qualifications, and experiences.

profile_task:
  description: >
    Compile a detailed personal and professional profile 
    using the GitHub ({github_url}) URLs, and personal write-up 
    ({personal_writeup}). Utilize tools to extract and 
    synthesize information from these sources.
  expected_output: >
    A comprehensive profile document that includes skills, 
    project experiences, contributions, interests, and 
    communication style.

resume_strategy_task:
  description: >
    Using the profile and job requirements obtained from 
    previous tasks, tailor the resume to highlight the most 
    relevant areas. Employ tools to adjust and enhance the 
    resume content. Make sure this is the best resume even but 
    don't make up any information. Update every section, 
    including the initial summary, work experience, skills, 
    and education. All to better reflect the candidate's 
    abilities and how it matches the job posting.
  expected_output: >
    An updated resume that effectively highlights the candidate's 
    qualifications and experiences relevant to the job.


interview_preparation_task:
  description: >
    Create a set of potential interview questions and talking 
    points based on the tailored resume and job requirements. 
    Utilize tools to generate relevant questions and discussion 
    points. Make sure to use these question and talking points to 
    help the candidate highlight the main points of the resume 
    and how it matches the job posting.
  expected_output: >
    A document containing key questions and talking points 
    that the candidate should prepare for the initial interview.
